dist: trusty
cache:
  - apt


install:
  - sudo apt-get install graphviz debhelper python2.7 python-setuptools python3 python3-setuptool

script:
  - export PATH=/usr/bin:${PATH}
  - dpkg-buildpackage -uc -us
