dist: trusty
cache:
  - apt


install:
  - sudo apt-get install graphviz debhelper python-all python-setuptools python3-all python3-setuptools

script:
  - export PATH=/usr/bin:${PATH}
  - dpkg-buildpackage -uc -us
  - lintian ../xtdmake_*.deb
